#!/bin/python3.12

import subprocess
import time
import sys
import json
import xml.etree.ElementTree as ET

class bcolors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKCYAN = '\033[96m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'


def handle_temps(temps):
    output = {}
    # Get the CPU temperature
    cpu_temp = temps["coretemp-isa-0000"]["Package id 0"]["temp1_input"]
    # Get the ACPI temperature
    acpi_temp = temps["acpitz-acpi-0"]["temp1"]["temp1_input"]
    output["CPU\t(°C)"] = cpu_temp
    output["ACPI\t(°C)"] = acpi_temp
    for core in temps["coretemp-isa-0000"]:
        if "Core" not in core: continue
        index = int(core.split(" ")[1])
        output[f"CORE#{index}\t(°C)"] = temps["coretemp-isa-0000"][core][f"temp{index + 2}_input"]
    return output

def handle_nvidia(nvidia):
    # gpu subelement --> temperature subelement
    gpu_temp = nvidia.find("gpu").find("temperature").find("gpu_temp").text
    return {"GPU\t(°C)": float(gpu_temp.split(" ")[0])}

def get_temps():
    # Get the temperatures from the sensors as JSON
    temps = subprocess.check_output(["sensors", "-j"])
    # Get the nvidia-smi output as XML
    nvidia = subprocess.check_output(["nvidia-smi", "-q", "-x"])
    # Parse the JSON and XML
    temps = json.loads(temps)
    nvidia = ET.fromstring(nvidia)
    # concatenate the two dictionaries
    return handle_temps(temps) | handle_nvidia(nvidia)

if __name__ == "__main__":

    if len(sys.argv) > 1 and (sys.argv[1] == "--help" or sys.argv[1] == "-h"):
        print("A Python script useful to keep an eye on device's temperatures. It includes information about the CPU, each CORE and the GPU.\n")
        print(bcolors.UNDERLINE + "Usage:" + bcolors.ENDC + " temps [OPTION]\n")
        print(bcolors.UNDERLINE + "Options\033[0m:" + bcolors.ENDC)
        print("  -s <TIME>")
        print("\tChange fetching interval in seconds (min 0.2s)\n")
        print("  -h, --help")
        print("\tPrint this message")
        sys.exit(0)

    # Interval has to be int and greater than 0, passed via 'python3 temps.py -s <interval>'
    try:
        interval = sys.argv[sys.argv.index("-s") + 1] if "-s" in sys.argv and sys.argv[sys.argv.index("-s")] else 1
    except IndexError:
        print(bcolors.FAIL + "error:" + bcolors.ENDC + " you must specify an interval of at least 0.2s\n")
        print(bcolors.UNDERLINE + "Usage:" + bcolors.ENDC + " temps -s <TIME>\n")
        print("See -h or --help for more information")
        sys.exit(0)

    if float(interval) < 0.2:
        print("Interval must be at least 0.2s")
        sys.exit(0)
    
    prev = {}
    try:
        while True:
            # Clear the screen
            print("\033c", end="")
            # Get the temperatures and print them
            json_output, output, separator = get_temps(), "", f">>>"
            for key, value in json_output.items():
                if key not in prev: prev[key] = value
                # Calculate the difference between the current and previous temperature
                delta = float(value) - float(prev.get(key, 0))
                # Color the delta based on the sign and stringify it
                delta = f"+{delta}" if delta > 0 else f"{delta}" if delta < 0 else f"+{delta}"
                output += f"{key}\t{separator}\t{value} ({delta}°C {interval}s delta)\n"
            print(f"Fetching Temperatures every {interval}s ({time.ctime()})")
            print("Press Ctrl+C to exit")
            print(output)
            prev = json_output
            time.sleep(float(interval))
    except KeyboardInterrupt:
        print("\nExiting...")
